export const INDONESIAN_PROVINCES = [
    { label: "Aceh", value: "Aceh" },
    { label: "Sumatera Utara", value: "Sumatera Utara" },
    { label: "Sumatera Barat", value: "Sumatera Barat" },
    { label: "Riau", value: "Riau" },
    { label: "Kepulauan Riau", value: "Kepulauan Riau" },
    { label: "Jambi", value: "Jambi" },
    { label: "Sumatera Selatan", value: "Sumatera Selatan" },
    { label: "Bengkulu", value: "Bengkulu" },
    { label: "Lampung", value: "Lampung" },
    { label: "Bangka Belitung", value: "Bangka Belitung" },
    { label: "Banten", value: "Banten" },
    { label: "DKI Jakarta", value: "DKI Jakarta" },
    { label: "Jawa Barat", value: "Jawa Barat" },
    { label: "Jawa Tengah", value: "Jawa Tengah" },
    { label: "DI Yogyakarta", value: "DI Yogyakarta" },
    { label: "Jawa Timur", value: "Jawa Timur" },
    { label: "Bali", value: "Bali" },
    { label: "Nusa Tenggara Barat", value: "Nusa Tenggara Barat" },
    { label: "Nusa Tenggara Timur", value: "Nusa Tenggara Timur" },
    { label: "Kalimantan Barat", value: "Kalimantan Barat" },
    { label: "Kalimantan Tengah", value: "Kalimantan Tengah" },
    { label: "Kalimantan Selatan", value: "Kalimantan Selatan" },
    { label: "Kalimantan Timur", value: "Kalimantan Timur" },
    { label: "Kalimantan Utara", value: "Kalimantan Utara" },
    { label: "Sulawesi Utara", value: "Sulawesi Utara" },
    { label: "Gorontalo", value: "Gorontalo" },
    { label: "Sulawesi Tengah", value: "Sulawesi Tengah" },
    { label: "Sulawesi Barat", value: "Sulawesi Barat" },
    { label: "Sulawesi Selatan", value: "Sulawesi Selatan" },
    { label: "Sulawesi Tenggara", value: "Sulawesi Tenggara" },
    { label: "Maluku", value: "Maluku" },
    { label: "Maluku Utara", value: "Maluku Utara" },
    { label: "Papua", value: "Papua" },
    { label: "Papua Barat", value: "Papua Barat" },
    { label: "Papua Pegunungan (provinsi baru)", value: "Papua Pegunungan (provinsi baru)" },
    { label: "Papua Tengah (provinsi baru)", value: "Papua Tengah (provinsi baru)" },
    { label: "Papua Selatan (provinsi baru)", value: "Papua Selatan (provinsi baru)" },
    { label: "Papua Barat Daya (provinsi baru)", value: "Papua Barat Daya (provinsi baru)" },
];