// File: allCities.js

export const ALL_CITIES = [
    { label: "Ambon", value: "Ambon" },
    { label: "Balikpapan", value: "Balikpapan" },
    { label: "Banda Aceh", value: "Banda Aceh" },
    { label: "Bandar Lampung", value: "Bandar Lampung" },
    { label: "Bandung", value: "Bandung" },
    { label: "Banjar", value: "Banjar" },
    { label: "Banjarbaru", value: "Banjarbaru" },
    { label: "Banjarmasin", value: "Banjarmasin" },
    { label: "Batam", value: "Batam" },
    { label: "Batu", value: "Batu" },
    { label: "Baubau", value: "Baubau" },
    { label: "Bekasi", value: "Bekasi" },
    { label: "Bengkulu", value: "Bengkulu" },
    { label: "Bima", value: "Bima" },
    { label: "Binjai", value: "Binjai" },
    { label: "Bitung", value: "Bitung" },
    { label: "Blitar", value: "Blitar" },
    { label: "Bogor", value: "Bogor" },
    { label: "Bontang", value: "Bontang" },
    { label: "Bukittinggi", value: "Bukittinggi" },
    { label: "Cilegon", value: "Cilegon" },
    { label: "Cimahi", value: "Cimahi" },
    { label: "Cirebon", value: "Cirebon" },
    { label: "Denpasar", value: "Denpasar" },
    { label: "Depok", value: "Depok" },
    { label: "Dumai", value: "Dumai" },
    { label: "Gorontalo", value: "Gorontalo" },
    { label: "Gunungsitoli", value: "Gunungsitoli" },
    { label: "Jakarta Barat", value: "Jakarta Barat" },
    { label: "Jakarta Pusat", value: "Jakarta Pusat" },
    { label: "Jakarta Selatan", value: "Jakarta Selatan" },
    { label: "Jakarta Timur", value: "Jakarta Timur" },
    { label: "Jakarta Utara", value: "Jakarta Utara" },
    { label: "Jambi", value: "Jambi" },
    { label: "Jayapura", value: "Jayapura" },
    { label: "Kediri", value: "Kediri" },
    { label: "Kendari", value: "Kendari" },
    { label: "Kotamobagu", value: "Kotamobagu" },
    { label: "Kupang", value: "Kupang" },
    { label: "Langsa", value: "Langsa" },
    { label: "Lhokseumawe", value: "Lhokseumawe" },
    { label: "Lubuklinggau", value: "Lubuklinggau" },
    { label: "Madiun", value: "Madiun" },
    { label: "Magelang", value: "Magelang" },
    { label: "Makassar", value: "Makassar" },
    { label: "Malang", value: "Malang" },
    { label: "Mamuju", value: "Mamuju" },
    { label: "Manado", value: "Manado" },
    { label: "Mataram", value: "Mataram" },
    { label: "Medan", value: "Medan" },
    { label: "Merauke", value: "Merauke" },
    { label: "Metro", value: "Metro" },
    { label: "Mojokerto", value: "Mojokerto" },
    { label: "Nabire", value: "Nabire" },
    { label: "Padang", value: "Padang" },
    { label: "Padang Panjang", value: "Padang Panjang" },
    { label: "Padang Sidempuan", value: "Padang Sidempuan" },
    { label: "Pagar Alam", value: "Pagar Alam" },
    { label: "Palangka Raya", value: "Palangka Raya" },
    { label: "Palembang", value: "Palembang" },
    { label: "Palopo", value: "Palopo" },
    { label: "Palu", value: "Palu" },
    { label: "Pangkalpinang", value: "Pangkalpinang" },
    { label: "Parepare", value: "Parepare" },
    { label: "Pariaman", value: "Pariaman" },
    { label: "Pasuruan", value: "Pasuruan" },
    { label: "Payakumbuh", value: "Payakumbuh" },
    { label: "Pekalongan", value: "Pekalongan" },
    { label: "Pekanbaru", value: "Pekanbaru" },
    { label: "Pematangsiantar", value: "Pematangsiantar" },
    { label: "Pontianak", value: "Pontianak" },
    { label: "Prabumulih", value: "Prabumulih" },
    { label: "Probolinggo", value: "Probolinggo" },
    { label: "Sabang", value: "Sabang" },
    { label: "Salatiga", value: "Salatiga" },
    { label: "Samarinda", value: "Samarinda" },
    { label: "Sawahlunto", value: "Sawahlunto" },
    { label: "Semarang", value: "Semarang" },
    { label: "Serang", value: "Serang" },
    { label: "Sibolga", value: "Sibolga" },
    { label: "Singkawang", value: "Singkawang" },
    { label: "Solok", value: "Solok" },
    { label: "Sorong", value: "Sorong" },
    { label: "Subulussalam", value: "Subulussalam" },
    { label: "Sukabumi", value: "Sukabumi" },
    { label: "Sungai Penuh", value: "Sungai Penuh" },
    { label: "Surabaya", value: "Surabaya" },
    { label: "Surakarta (Solo)", value: "Surakarta (Solo)" },
    { label: "Tangerang", value: "Tangerang" },
    { label: "Tangerang Selatan", value: "Tangerang Selatan" },
    { label: "Tanjungbalai", value: "Tanjungbalai" },
    { label: "Tanjungpinang", value: "Tanjungpinang" },
    { label: "Tarakan", value: "Tarakan" },
    { label: "Tasikmalaya", value: "Tasikmalaya" },
    { label: "Tebing Tinggi", value: "Tebing Tinggi" },
    { label: "Tegal", value: "Tegal" },
    { label: "Ternate", value: "Ternate" },
    { label: "Tidore Kepulauan", value: "Tidore Kepulauan" },
    { label: "Tomohon", value: "Tomohon" },
    { label: "Tual", value: "Tual" },
    { label: "Wamena", value: "Wamena" },
    { label: "Yogyakarta", value: "Yogyakarta" },
];