export const UIKA_WORK_UNITS = [
    { label: "Universitas Ibn Khaldun", value: "1" },
    { label: "Fakultas Keguruan dan Ilmu Pendidikan", value: "2" },
    { label: "Pendidikan Vokasional Desain Fashion", value: "3" },
    { label: "Pendidikan Matematika", value: "4" },
    { label: "Teknologi Pendidikan", value: "5" },
    { label: "Pendidikan Masyarakat", value: "6" },
    { label: "Pendidikan Profesi Guru", value: "7" },
    { label: "Pendidikan Bahasa Inggris", value: "8" },
    { label: "Fakultas Hukum", value: "9" },
    { label: "Ilmu Hukum", value: "10" },
    { label: "Fakultas Ekonomi dan Bisnis", value: "11" },
    { label: "Perbankan dan Keuangan Digital", value: "12" },
    { label: "Perdagangan Internasional", value: "13" },
    { label: "Bisnis Digital", value: "14" },
    { label: "Akuntansi", value: "15" },
    { label: "Manajemen", value: "16" },
    { label: "Fakultas Agama Islam", value: "17" },
    { label: "Bimbingan dan Konseling Pendidikan Islam", value: "18" },
    { label: "Pendidikan Agama Islam", value: "19" },
    { label: "Ahwal Al Syakshiyah", value: "20" },
    { label: "Komunikasi dan Penyiaran Islam", value: "21" },
    { label: "Ekonomi Syariah", value: "22" },
    { label: "Pendidikan Guru Madrasah Ibtidaiyah", value: "23" },
    { label: "Manajemen Haji dan Umrah", value: "24" },
    { label: "Ilmu Al-Qu`an dan Tafsir", value: "25" },
    { label: "Fakultas Teknik dan Sains", value: "26" },
    { label: "Ilmu Lingkungan", value: "27" },
    { label: "Sistem Informasi", value: "28" },
    { label: "Rekayasa Pertanian dan Biosistem", value: "29" },
    { label: "Teknik Elektro", value: "30" },
    { label: "Teknik Sipil", value: "31" },
    { label: "Teknik Mesin", value: "32" },
    { label: "Teknik Informatika", value: "33" },
    { label: "Sekolah Pascasarjana", value: "34" },
    { label: "Manajemen (S2)", value: "35" },
    { label: "Pendidikan Agama Islam (S2)", value: "36" },
    { label: "Hukum Bisnis (S2)", value: "37" },
    { label: "Ekonomi Syariah (S3)", value: "38" },
    { label: "Pendidikan Agama Islam (S3)", value: "39" },
    { label: "Teknologi Pendidikan (S2)", value: "40" },
    { label: "Ekonomi Syariah (S2)", value: "41" },
    { label: "Komunikasi Penyiaran islam (S2)", value: "42" },
    { label: "Fakultas Ilmu Kesehatan", value: "43" },
    { label: "Gizi", value: "44" },
    { label: "Kesehatan Masyarakat", value: "45" },
    { label: "Biro Administrasi Akademik dan Kemahasiswaan", value: "46" },
    { label: "Unit Perpustakaan", value: "47" },
    { label: "Mata Kuliah Wajib Kurikulum", value: "48" },
    { label: "Biro Perencanaan, Pelaporan dan Sistem Informasi", value: "49" },
    { label: "Pendidikan Luar Sekolah", value: "50" },
];