export const INDONESIAN_BANKS = [
    { label: "Bank Aceh Syariah", value: "Bank Aceh Syariah" },
    { label: "Bank Aladin Syariah", value: "Bank Aladin Syariah" },
    { label: "Bank Amar Indonesia", value: "Bank Amar Indonesia" },
    { label: "Bank Artha Graha Internasional", value: "Bank Artha Graha Internasional" },
    { label: "Bank BJB", value: "Bank BJB" },
    { label: "Bank BJB Syariah", value: "Bank BJB Syariah" },
    { label: "Bank BNI (Bank Negara Indonesia)", value: "Bank BNI" },
    { label: "Bank BPD Bali", value: "Bank BPD Bali" },
    { label: "Bank BPD DIY", value: "Bank BPD DIY" },
    { label: "Bank BPR (Bank Perekonomian Rakyat)", value: "Bank BPR" },
    { label: "Bank BRI (Bank Rakyat Indonesia)", value: "Bank BRI" },
    { label: "Bank BSI (Bank Syariah Indonesia)", value: "Bank BSI" },
    { label: "Bank BTN (Bank Tabungan Negara)", value: "Bank BTN" },
    { label: "Bank BTPN (Bank Tabungan Pensiunan Nasional)", value: "Bank BTPN" },
    { label: "Bank BTPN Syariah", value: "Bank BTPN Syariah" },
    { label: "Bank Bukopin", value: "Bank Bukopin" },
    { label: "Bank Bumi Arta", value: "Bank Bumi Arta" },
    { label: "Bank Capital Indonesia", value: "Bank Capital Indonesia" },
    { label: "Bank BCA (Bank Central Asia)", value: "Bank BCA" },
    { label: "Bank BCA Syariah", value: "Bank BCA Syariah" },
    { label: "Bank CIMB Niaga", value: "Bank CIMB Niaga" },
    { label: "Bank Danamon", value: "Bank Danamon" },
    { label: "Bank DBS Indonesia", value: "Bank DBS Indonesia" },
    { label: "Bank DKI", value: "Bank DKI" },
    { label: "Bank Ganesha", value: "Bank Ganesha" },
    { label: "Bank Jago", value: "Bank Jago" },
    { label: "Bank Jambi", value: "Bank Jambi" },
    { label: "Bank Jasa Jakarta", value: "Bank Jasa Jakarta" },
    { label: "Bank Jateng", value: "Bank Jateng" },
    { label: "Bank Jatim", value: "Bank Jatim" },
    { label: "Bank Kalbar", value: "Bank Kalbar" },
    { label: "Bank Mandiri", value: "Bank Mandiri" },
    { label: "Bank Maspion", value: "Bank Maspion" },
    { label: "Bank Mayapada", value: "Bank Mayapada" },
    { label: "Bank Maybank Indonesia", value: "Bank Maybank Indonesia" },
    { label: "Bank Mega", value: "Bank Mega" },
    { label: "Bank Mega Syariah", value: "Bank Mega Syariah" },
    { label: "Bank Mestika Dharma", value: "Bank Mestika Dharma" },
    { label: "Bank MNC Internasional", value: "Bank MNC Internasional" },
    { label: "Bank Muamalat", value: "Bank Muamalat" },
    { label: "Bank Nagari", value: "Bank Nagari" },
    { label: "Bank Nationalnobu", value: "Bank Nationalnobu" },
    { label: "Bank Neo Commerce", value: "Bank Neo Commerce" },
    { label: "Bank OCBC NISP", value: "Bank OCBC NISP" },
    { label: "Bank Panin", value: "Bank Panin" },
    { label: "Bank Panin Dubai Syariah", value: "Bank Panin Dubai Syariah" },
    { label: "Bank Permata", value: "Bank Permata" },
    { label: "Bank QNB Indonesia", value: "Bank QNB Indonesia" },
    { label: "Bank Resona Perdania", value: "Bank Resona Perdania" },
    { label: "Bank Seabank Indonesia", value: "Bank Seabank Indonesia" },
    { label: "Bank Shinhan Indonesia", value: "Bank Shinhan Indonesia" },
    { label: "Bank Sinarmas", value: "Bank Sinarmas" },
    { label: "Bank Sulselbar", value: "Bank Sulselbar" },
    { label: "Bank Sumsel Babel", value: "Bank Sumsel Babel" },
    { label: "Bank Sumut", value: "Bank Sumut" },
    { label: "Bank UOB Indonesia", value: "Bank UOB Indonesia" },
    { label: "Bank Victoria Internasional", value: "Bank Victoria Internasional" },
    { label: "Bank Woori Saudara", value: "Bank Woori Saudara" },
    { label: "Citibank", value: "Citibank" },
    { label: "HSBC Indonesia", value: "HSBC Indonesia" },
    { label: "JPMorgan Chase", value: "JPMorgan Chase" },
    { label: "Standard Chartered", value: "Standard Chartered" },
];