export const COUNTRIES = [
    { value: "AF", label: "Afghanistan" },
    { value: "AL", label: "Albania" },
    { value: "DZ", label: "Aljazair (Algeria)" },
    { value: "AD", label: "Andorra" },
    { value: "AO", label: "Angola" },
    { value: "AG", label: "Antigua dan Barbuda" },
    { value: "SA", label: "Arab Saudi" },
    { value: "AR", label: "Argentina" },
    { value: "AM", label: "Armenia" },
    { value: "AU", label: "Australia" },
    { value: "AT", label: "Austria" },
    { value: "AZ", label: "Azerbaijan" },
    { value: "BS", label: "Bahama" },
    { value: "BH", label: "Bahrain" },
    { value: "BD", label: "Bangladesh" },
    { value: "BB", label: "Barbados" },
    { value: "NL", label: "Belanda (Netherlands)" },
    { value: "BY", label: "Belarus" },
    { value: "BE", label: "Belgia (Belgium)" },
    { value: "BZ", label: "Belize" },
    { value: "BJ", label: "Benin" },
    { value: "BT", label: "Bhutan" },
    { value: "BO", label: "Bolivia" },
    { value: "BA", label: "Bosnia dan Herzegovina" },
    { value: "BW", label: "Botswana" },
    { value: "BR", label: "Brasil (Brazil)" },
    { value: "BN", label: "Brunei Darussalam" },
    { value: "BG", label: "Bulgaria" },
    { value: "BF", label: "Burkina Faso" },
    { value: "BI", label: "Burundi" },
    { value: "TD", label: "Chad" },
    { value: "CL", label: "Chili (Chile)" },
    { value: "CN", label: "China (Tiongkok)" },
    { value: "CY", label: "Siprus (Cyprus)" },
    { value: "CO", label: "Kolombia (Colombia)" },
    { value: "KM", label: "Komoro (Comoros)" },
    { value: "CG", label: "Kongo - Brazzaville" },
    { value: "CD", label: "Kongo - Kinshasa (DRC)" },
    { value: "CR", label: "Kosta Rika (Costa Rica)" },
    { value: "HR", label: "Kroasia (Croatia)" },
    { value: "CU", label: "Kuba (Cuba)" },
    { value: "DK", label: "Denmark" },
    { value: "DM", label: "Dominika" },
    { value: "DO", label: "Republik Dominika" },
    { value: "DJ", label: "Djibouti" },
    { value: "EC", label: "Ekuador (Ecuador)" },
    { value: "EG", label: "Mesir (Egypt)" },
    { value: "SV", label: "El Salvador" },
    { value: "ER", label: "Eritrea" },
    { value: "EE", label: "Estonia" },
    { value: "SZ", label: "Eswatini (Swaziland)" },
    { value: "ET", label: "Ethiopia" },
    { value: "FJ", label: "Fiji" },
    { value: "PH", label: "Filipina (Philippines)" },
    { value: "FI", label: "Finlandia (Finland)" },
    { value: "FR", label: "Prancis (France)" },
    { value: "GA", label: "Gabon" },
    { value: "GM", label: "Gambia" },
    { value: "GE", label: "Georgia" },
    { value: "GH", label: "Ghana" },
    { value: "GR", label: "Yunani (Greece)" },
    { value: "GD", label: "Grenada" },
    { value: "GT", label: "Guatemala" },
    { value: "GN", label: "Guinea" },
    { value: "GW", label: "Guinea-Bissau" },
    { value: "GQ", label: "Guinea Ekuatorial" },
    { value: "GY", label: "Guyana" },
    { value: "HT", label: "Haiti" },
    { value: "HN", label: "Honduras" },
    { value: "HK", label: "Hong Kong" },
    { value: "HU", label: "Hungaria (Hungary)" },
    { value: "IS", label: "Islandia (Iceland)" },
    { value: "IN", label: "India" },
    { value: "ID", label: "Indonesia" },
    { value: "IR", label: "Iran" },
    { value: "IQ", label: "Irak" },
    { value: "IE", label: "Irlandia (Ireland)" },
    { value: "IL", label: "Israel" },
    { value: "IT", label: "Italia (Italy)" },
    { value: "JM", label: "Jamaika (Jamaica)" },
    { value: "JP", label: "Jepang (Japan)" },
    { value: "JO", label: "Yordania (Jordan)" },
    { value: "KZ", label: "Kazakhstan" },
    { value: "KE", label: "Kenya" },
    { value: "KI", label: "Kiribati" },
    { value: "KR", label: "Korea Selatan" },
    { value: "KP", label: "Korea Utara" },
    { value: "XK", label: "Kosovo" },
    { value: "KW", label: "Kuwait" },
    { value: "KG", label: "Kyrgyzstan" },
    { value: "LA", label: "Laos" },
    { value: "LV", label: "Latvia" },
    { value: "LB", label: "Lebanon" },
    { value: "LS", label: "Lesotho" },
    { value: "LR", label: "Liberia" },
    { value: "LY", label: "Libya" },
    { value: "LI", label: "Liechtenstein" },
    { value: "LT", label: "Lituania (Lithuania)" },
    { value: "LU", label: "Luksemburg (Luxembourg)" },
    { value: "MK", label: "Makedonia Utara" },
    { value: "MG", label: "Madagaskar" },
    { value: "MW", label: "Malawi" },
    { value: "MY", label: "Malaysia" },
    { value: "MV", label: "Maladewa (Maldives)" },
    { value: "ML", label: "Mali" },
    { value: "MT", label: "Malta" },
    { value: "MH", label: "Kepulauan Marshall" },
    { value: "MR", label: "Mauritania" },
    { value: "MU", label: "Mauritius" },
    { value: "MX", label: "Meksiko (Mexico)" },
    { value: "FM", label: "Mikronesia" },
    { value: "MD", label: "Moldova" },
    { value: "MC", label: "Monako (Monaco)" },
    { value: "MN", label: "Mongolia" },
    { value: "ME", label: "Montenegro" },
    { value: "MA", label: "Maroko (Morocco)" },
    { value: "MZ", label: "Mozambik" },
    { value: "MM", label: "Myanmar (Burma)" },
    { value: "NA", label: "Namibia" },
    { value: "NR", label: "Nauru" },
    { value: "NP", label: "Nepal" },
    { value: "NZ", label: "Selandia Baru (New Zealand)" },
    { value: "NI", label: "Nikaragua (Nicaragua)" },
    { value: "NE", label: "Niger" },
    { value: "NG", label: "Nigeria" },
    { value: "NO", label: "Norwegia (Norway)" },
    { value: "OM", label: "Oman" },
    { value: "PK", label: "Pakistan" },
    { value: "PW", label: "Palau" },
    { value: "PA", label: "Panama" },
    { value: "PG", label: "Papua Nugini" },
    { value: "PY", label: "Paraguay" },
    { value: "PE", label: "Peru" },
    { value: "PL", label: "Polandia (Poland)" },
    { value: "PT", label: "Portugal" },
    { value: "QA", label: "Qatar" },
    { value: "RO", label: "Rumania (Romania)" },
    { value: "RU", label: "Rusia (Russia)" },
    { value: "RW", label: "Rwanda" },
    { value: "KN", label: "Saint Kitts dan Nevis" },
    { value: "LC", label: "Saint Lucia" },
    { value: "VC", label: "Saint Vincent dan Grenadines" },
    { value: "WS", label: "Samoa" },
    { value: "SM", label: "San Marino" },
    { value: "ST", label: "Sao Tome dan Principe" },
    { value: "SN", label: "Senegal" },
    { value: "RS", label: "Serbia" },
    { value: "SC", label: "Seychelles" },
    { value: "SL", label: "Sierra Leone" },
    { value: "SG", label: "Singapura (Singapore)" },
    { value: "SK", label: "Slovakia" },
    { value: "SI", label: "Slovenia" },
    { value: "SB", label: "Kepulauan Solomon" },
    { value: "SO", label: "Somalia" },
    { value: "ZA", label: "Afrika Selatan (South Africa)" },
    { value: "SS", label: "Sudan Selatan" },
    { value: "ES", label: "Spanyol (Spain)" },
    { value: "LK", label: "Sri Lanka" },
    { value: "SD", label: "Sudan" },
    { value: "SR", label: "Suriname" },
    { value: "SE", label: "Swedia (Sweden)" },
    { value: "CH", label: "Swiss (Switzerland)" },
    { value: "SY", label: "Suriah (Syria)" },
    { value: "TW", label: "Taiwan" },
    { value: "TJ", label: "Tajikistan" },
    { value: "TZ", label: "Tanzania" },
    { value: "TH", label: "Thailand" },
    { value: "TL", label: "Timor Leste" },
    { value: "TG", label: "Togo" },
    { value: "TO", label: "Tonga" },
    { value: "TT", label: "Trinidad dan Tobago" },
    { value: "TN", label: "Tunisia" },
    { value: "TR", label: "Turki (Turkey)" },
    { value: "TM", label: "Turkmenistan" },
    { value: "TV", label: "Tuvalu" },
    { value: "UG", label: "Uganda" },
    { value: "UA", label: "Ukraina (Ukraine)" },
    { value: "AE", label: "Uni Emirat Arab" },
    { value: "GB", label: "Inggris (United Kingdom)" },
    { value: "US", label: "Amerika Serikat (United States)" },
    { value: "UY", label: "Uruguay" },
    { value: "UZ", label: "Uzbekistan" },
    { value: "VU", label: "Vanuatu" },
    { value: "VA", label: "Vatikan" },
    { value: "VE", label: "Venezuela" },
    { value: "VN", label: "Vietnam" },
    { value: "YE", label: "Yaman (Yemen)" },
    { value: "ZM", label: "Zambia" },
    { value: "ZW", "label": "Zimbabwe" },
];